export const TypographyVariants = {
  fontFamily: "Inter",
  fontWeightRegular: 400,
  fontWeightMedium: 500,
  fontWeightBold: 700,

  h1: {
    fontFamily: "Inter",
    fontWeight: 700,
    fontSize: "36px",
    lineHeight: "1.25",
  },
  h2: {
    fontFamily: "Inter",
    fontWeight: 700,
    fontSize: "30px",
    lineHeight: "1.3",
  },
  h3: {
    fontFamily: "Inter",
    fontWeight: 600,
    fontSize: "24px",
    lineHeight: "1.375",
  },
  h4: {
    fontFamily: "Inter",
    fontWeight: 600,
    fontSize: "20px",
    lineHeight: "1.5",
  },
  body1: {
    fontFamily: "Inter",
    fontWeight: 400,
    fontSize: "16px",
    lineHeight: "1.5",
  },
  body2: {
    fontFamily: "Inter",
    fontWeight: 400,
    fontSize: "14px",
    lineHeight: "1.43",
  },
  caption: {
    fontFamily: "Inter",
    fontWeight: 400,
    fontSize: "12px",
    lineHeight: "1.5",
  },
  "large-semibold": {
    fontFamily: "Inter",
    fontWeight: 600,
    fontSize: "18px",
    lineHeight: "1.5",
  },
  "subtle-semibold": {
    fontFamily: "Inter",
    fontWeight: 600,
    fontSize: "14px",
    lineHeight: "1.5",
  },
  "body-medium": {
    fontFamily: "Inter",
    fontWeight: 500,
    fontSize: "16px",
    lineHeight: "1.5",
  },
  "subtle-medium": {
    fontFamily: "Inter",
    fontWeight: 500,
    fontSize: "14px",
    lineHeight: "1.5",
  },
  detail: {
    fontFamily: "Inter",
    fontWeight: 400,
    fontSize: "12px",
    lineHeight: "1.5",
  },
  "detail-medium": {
    fontFamily: "Inter",
    fontWeight: 500,
    fontSize: "12px",
    lineHeight: "1.5",
  },
  "lead-regular": {
    fontFamily: "Inter",
    fontWeight: 400,
    fontSize: "18px",
    lineHeight: "1.5",
  },
  "subtle-regular": {
    fontFamily: "Inter",
    fontWeight: 400,
    fontSize: "14px",
    lineHeight: "1.5",
  },
  "p-light": {
    fontFamily: "Inter",
    fontWeight: 300,
    fontSize: "16px",
    lineHeight: "1.5",
  },
  "p-regular": {
    fontFamily: "Inter",
    fontWeight: 400,
    fontSize: "16px",
    lineHeight: "1.5",
  },
  "p-medium": {
    fontFamily: "Inter",
    fontWeight: 500,
    fontSize: "16px",
    lineHeight: "1.5",
  },
  "p-ui": {
    fontFamily: "Inter",
    fontWeight: 400,
    fontSize: "16px",
    lineHeight: "1.5",
  },
  "list-light": {
    fontFamily: "Inter",
    fontWeight: 300,
    fontSize: "16px",
    lineHeight: "1.5",
  },
};
